// `.open-next/worker.js` is generated by `opennextjs-cloudflare build` and doesn't exist before the first
// build — @ts-ignore (not @ts-expect-error) because whether this errors depends on build state.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { default as nextHandler } from "./.open-next/worker.js";
import { getAdminClient } from "./lib/checker/db";
import { runMinuteCheck } from "./lib/checker/minuteCheck";
import { runHourlyRollup } from "./lib/checker/hourlyRollup";
import { runDailyRollup } from "./lib/checker/dailyRollup";
import type { CheckerEnv } from "./lib/checker/types";

export default {
  fetch: nextHandler.fetch,

  async scheduled(controller: ScheduledController, env: CheckerEnv) {
    const db = getAdminClient(env);

    switch (controller.cron) {
      case "* * * * *":
        await runMinuteCheck(db, env.HEALTH_CHECK_SECRET);
        break;
      case "0 * * * *":
        await runHourlyRollup(db);
        break;
      case "5 0 * * *":
        await runDailyRollup(db);
        break;
      default:
        console.warn(`Unhandled cron trigger: ${controller.cron}`);
    }
  },
} satisfies ExportedHandler<CheckerEnv>;
