// `.open-next/worker.js` is generated by `opennextjs-cloudflare build` and doesn't exist before the first
// build — @ts-ignore (not @ts-expect-error) because whether this errors depends on build state.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { default as nextHandler } from "./.open-next/worker.js";

// Serves the dashboard only. Health checks + rollups run in the separate,
// lightweight `ys-status-checker` worker (see checker/index.ts) — running them
// here pulled the whole Next.js bundle into every cron invocation and kept
// hitting the Workers Free plan's 10ms CPU limit.
export default {
  fetch: nextHandler.fetch,
} satisfies ExportedHandler;
